<a href="https://colab.research.google.com/github/kiryu-3/Prmn2023/blob/main/Python/Python_Basic/question/PythonBasic24_5_Question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DSライブラリ1 課題

In [ ]:
# 最初に実行してください
import numpy as np
import pandas as pd

## 課題1

以下のnumpy行列を、2種類の方法で作成してください。

``` py
[10 15 20 25 30 35 40 45 50]
```

`np.arange([start,]stop[,step])`

- start 以上 stop 未満の値を step ずつ増加させた値の array。  
- [　] は省略可能を意味する。  
- start と step は省略可能で、それぞれ 0 と 1 がデフォルトで入る。

参考サイト：[こちら](https://bit.ly/3qP27cQ)

`np.linspace(start,stop,num)`

- start以上stop未満の数をnum個で区切った値のarray。  
- stopを含むので注意が必要。  
- endpoint=Falseという引数で、stopの数字以下ではなく未満で結果を出力することができる。

参考サイト：[こちら](https://bit.ly/3Uq8lxc)

- 整数列を作りたいときは`arange()`
- グラフ作成で区間を細かく区切りたいときは`linspace()`

を使うことが多いです。

In [ ]:
# 入力用


## 課題2

以下のnumpy行列について、(1)～(3)のnumpy行列に変換してください。

In [ ]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

(1)   
```
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
```

(2)  
```
array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])
```

(3)  
```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
```

In [ ]:
# 入力用


### 課題2ヒント

`reshape（p, q）`

- p行q列の行列に変換
- 割り切れない数値では変換できない
- 値の順番はそのまま

参考サイト：[こちら](https://bit.ly/3QWHhD0)

`.T or transpose()`

- 転置（行と列を入れ替える操作）を行う
- 値の順番も変更される

`flatten()`

- 一発で1次元にする

## 課題3

以下の2つのnumpy行列について、(1)と(2)の問題に答えて下さい。

In [ ]:
ndarrayA = np.array([[1, 2], [3, 4]])
ndarrayA

array([[1, 2],
       [3, 4]])

In [ ]:
ndarrayB = np.array([[5, 6], [7, 8]])
ndarrayB

array([[5, 6],
       [7, 8]])

(1) 同じ要素番号同士の掛け算  
(2) 行列の掛け算

In [ ]:
# 入力用


### 課題3ヒント

| 演算                  | NumPy関数            |
|-----------------------|----------------------|
| aとbの足し算          | `a + b`, `np.add(a, b)`          |
| aとbの引き算          | `a - b`, `np.subtract(a, b)`    |
| aとbの掛け算          | `a * b`, `np.multiply(a, b)`    |
| aとbの割り算          | `a / b`                |
| aをbで割った商の整数部分 | `a // b`               |
| aをbで割った剰余（あまり）| `a % b`                |
| aのb乗               | `a ** b`, `np.power(a, b)`      |
| aの平方根             | `np.sqrt(a)`           |
| 行列Aと行列Bの要素積   | `A * B`                |
| 行列Aと行列Bの積       | `np.dot(A, B)`         |


## 課題4

以下のnumpy行列について、(1)～(3)の結果が返ってくるようコードを書いてください。

In [ ]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

(1)  `45`  
(2)  `array([ 6, 15, 24])`  
(3)  `array([12, 15, 18])`

In [ ]:
# 入力用


### 課題4ヒント

- `axis = 0` は行方向、`axis = 1` は列方向を意味する

## 課題5

以下のnumpy行列について、(1)～(5)の問題に答えて下さい。

![](https://imgur.com/ROBdIzz.png)

(1)  上のnumpy行列を定義し、出力してください。  
(2)  最後の行を取り出してください。  
(3)  4列目を取り出してください。  
(4)  赤枠で囲まれたところを取り出してください。  
(5)  偶数は0に、奇数は1に置き換えて下さい。

In [ ]:
# 入力用


### 課題5ヒント

`np.where（condition, a, b）`

- condition（条件式）がTrueの時はaに、Falseの時はbに置き換える。



## 課題6

以下のDataFrameについて、(1)～(5)の問題に答えてください。

![](https://imgur.com/MfBMjgn.png)

参考サイト：[こちら(Yutaka)](https://bit.ly/3DC3ymw)




(1)  上のDataFrameを定義し、出力してください。（参考サイト：[こちら](https://www.yutaka-note.com/entry/pandas_dict)）  
(2)  "name"列を取り出してください。  
(3)  "uni1"行を取り出してください。  
(4)  "name"列と"Age"列を取り出してください。  
(5)  "uni1"行と"uni2"行の"name"列と"Age"列を取り出してください。  
(6)  "Age"列の値が小さい順（昇順）にデータを並び替えてください。（参考サイト：[こちら](https://www.yutaka-note.com/entry/pandas_sort)）  
(7)  "Age"列の値が大きい順（降順）にデータを並び替えてください。  

In [ ]:
# 入力用


## 課題7

以下のDataFrameについて、(1)～(5)の問題に答えてください。

![](https://imgur.com/MfBMjgn.png)

(1)  上のDataFrameに、以下のデータを追加してください。  
![](https://imgur.com/PUfpiBm.png)   

(2)  以下のような表を出力して、欠損値の数とカラムのデータ型を確認してください。  
![](https://imgur.com/BVYwLGo.png)  

(3)  "sex"列の名前を**"kokuritu"**に変えたうえで、以下のようにデータを変換してください。  
　　**`"male"→True, "female"→False`**  
![](https://imgur.com/URjwbD7.png)

(4)  "kokuritu"列内のユニークな値とその出現回数を求めてください。  
![](https://imgur.com/VnL3mMc.png)

(5)  "kokuritu"列ごとの"Age"列の値の平均値を求めてください。（参考サイト：[こちら](https://www.yutaka-note.com/entry/pandas_groupby)）   
![](https://imgur.com/MOYk6w2.png)

(6)  欠損値のある行を削除した新しいDataFrameを作ってください（そのまま更新しない）。    
（参考サイト：[こちら](https://www.yutaka-note.com/entry/pandas_dropna)）    

(7)  欠損値を"Age"列の平均値で置き換えたDataFrameを作ってください。  
（参考サイト：[こちら](https://www.yutaka-note.com/entry/pandas_na#%E6%AC%A0%E6%90%8D%E5%80%A4%E3%81%AE%E8%A3%9C%E9%96%93fillna)）  

(8)  (7)で作ったDataFrameの、"Age"列の基本統計量を求めてください。  
![](https://imgur.com/OMTu4uW.png)

In [ ]:
# 入力用


### 課題7ヒント

欠損値の有無は、`df.info()`でも求めることができますが、  
`df.isnull().sum()`でも求めることができます。

＜出力結果例＞  
![](https://imgur.com/fPVG0ke.png)

また、`df.describe()`とすると数値型のカラムの基本統計量を求めることができますが、  
引数`include=['O']`を指定すると名義型のカラムの基本統計量も求めることができます。

＜出力結果例＞  
![](https://imgur.com/GUKIWbJ.png)